# Generated by Django 4.0.6 on 2022-12-04 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0002_course_student_createassign_attendance_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolled_course',
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enroll_course', to='MainApp.course'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=10)),
                ('rel_course', models.ManyToManyField(blank=True, related_name='staff_course', to='MainApp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leave_date', models.DateField()),
                ('note', models.TextField()),
                ('leave_state', models.CharField(choices=[('applied', 'Applied'), ('approve', 'Approve'), ('reject', 'Reject')], default=1, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leave', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
