# Generated by Django 4.0.6 on 2022-12-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_extended_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='createassign',
            name='questions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaves',
            name='leave_state',
            field=models.CharField(choices=[('applied', 'Applied'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=50),
        ),
    ]
