# Generated by Django 4.0.6 on 2022-12-04 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_createassign_questions_alter_leaves_leave_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sub_date',
            field=models.DateField(default=datetime.date(2022, 12, 5)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assign_state',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('notsubmitted', 'Not Submitted'), ('checked', 'Checked'), ('late', 'Delayed')], max_length=50),
        ),
    ]
