# Generated by Django 4.0.6 on 2022-12-05 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_assignment_sub_date_alter_assignment_assign_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='createassign',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='MainApp.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_assign', to='MainApp.createassign'),
        ),
    ]
